name: homed-zigbee
description: HOMEd ZigBee
url: https://wiki.u236.org/page/ZigBee
image: docker.u236.org/homed-zigbee
arch: [ amd64, aarch64, armv7 ]

# https://developers.home-assistant.io/docs/add-ons/configuration
version: 3.1.3
slug: homed
init: false
startup: application
homeassistant_api: true
map: [ "config:rw" ]
uart: true
