name: "HOMEd Zigbee"
version: 3.1.3
description: "HOMEd ZigBee"
slug: homed
arch:
  - amd64
  - aarch64
  - armv7
url: https://github.com/ANS-spb/hassio-addons/homed-zigbee
init: false
startup: application
map:
  - config:rw
uart: true
image: "docker.u236.org/homed-zigbee"
