name: "HOMEd Zigbee"
description: "HOMEd ZigBee"
url: https://github.com/ANS-spb/hassio-addons/homed-zigbee
image: docker.u236.org/homed-zigbee
arch: [ amd64, aarch64, armv7 ]

# https://developers.home-assistant.io/docs/add-ons/configuration
version: 3.1.3
slug: homed
init: false
startup: application
map: [ "config:rw" ]
uart: true
